name: "Version and toml checks"


on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.0"
    - name: Checks
      run: |
        python checks.py